services:
  postgres:
    # https://hub.docker.com/_/postgres
    image: postgres:17.6-trixie
    container_name: redmine-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - redmine_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redmine:
    # https://hub.docker.com/_/redmine
    image: redmine:6.1.0-trixie
    ports:
      - "3000:3000"
    container_name: redmine-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      REDMINE_DB_POSTGRES: ${REDMINE_DB_POSTGRES}
      REDMINE_DB_USERNAME: ${REDMINE_DB_USERNAME}
      REDMINE_DB_PASSWORD: ${REDMINE_DB_PASSWORD}
      REDMINE_DB_DATABASE: ${REDMINE_DB_DATABASE}
      REDMINE_PLUGINS_MIGRATE: ${REDMINE_PLUGINS_MIGRATE}
      REDMINE_SECRET_KEY_BASE: ${REDMINE_SECRET_KEY_BASE}
    volumes:
      - redmine_files:/usr/src/redmine/files
      - redmine_plugins:/usr/src/redmine/plugins
    networks:
      - redmine_network

networks:
  redmine_network:
    driver: bridge

volumes:
  postgres_data:
    external: true
  redmine_files:
    external: true
  redmine_plugins:
    external: true
